### ISSUE TITLE
Didn't work for me at all.

### ISSUE THREAD

**Issue by neocogent** [avinassh/isso-openshift#3]
Sad to say, but I tried this today and didn't work. 
I'm now in ssh console trying to dig around and find out why.

The method I used:
- openshift web interface - start a Python 2.7 gear with this repo as source. That worked.
- git clone to my system.
- edit production.cfg, commit, push back. 
- got message that app started failed.
- login with ssh, find logs and check
    **gunicorn not installed**
- tried to pip install that. worked. but now isso not installed.
- realized must be a virtualenv there. but trying to figure out now how to get correct python modules installed.
- seems requirements.txt was ignored.

**Comment by neocogent** [comment]
After more testing it seems configparser is no longer available in versions less than 3.5.0. I tried doing pip install on openshift container and got the error message.

I updated the requirements.txt to "configparser==3.5.0", and it built. Well, almost. It now seems there is no wheel for this one so it has to build and it fails on that:

```
remote: Building wheels for collected packages: configparser, ipaddr, itsdangerous, misaka, html5lib
remote: Exception:
remote: Traceback (most recent call last):
remote:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
remote:     status = self.run(options, args)
remote:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/commands/install.py", line 301, in run
remote:     wb.build(autobuilding=True)
remote:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/wheel.py", line 758, in build
remote:     ensure_dir(output_dir)
remote:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 70, in ensure_dir
remote:     os.makedirs(path)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 150, in makedirs
remote:     makedirs(head, mode)
remote:   File "/opt/rh/python27/root/usr/lib64/python2.7/os.py", line 157, in makedirs
remote:     mkdir(name, mode)
remote: OSError: [Errno 13] Permission denied: '/var/lib/openshift/5882cc672d5271459c00013c/.cache'
remote: 
```

Ugh! Half the time doing anything with python packages is such a hassle.
I don't know how to fix this now. It appears to be a screw up with permissions during build, which should fall on redhat's shoulders. I guess.

**Comment by avinassh** [comment]
I somehow forgot to respond to this. Did you figure out?

**Comment by neocogent** [comment]
It's been a while, but no. I gave up using it on openshift and installed it on another server. Now I don't have that server any more so it would still be nice to use openshift but I have not got back to trying again.

**Comment by avinassh** [comment]
I will check this weekend and try to figure out
